[package]
name = "wikidata-filter"
version = "0.1.0"
authors = ["Bastian Müller <bastian@turbolent.com>"]
edition = "2018"

[dependencies]
"bzip2" = "0.3.3"
"regex" = "1.2.1"
"lazy_static" = "1.3.0"
"lazy-static-include" = "2.2.0"
