- hosts:
  - localhost
  gather_facts: no
  tasks:

  - name: Ensure server exists
    local_action:
      module: vultr_server
      name: wikidata-filter
      os: "Debian 10 x64 (buster)"
      plan: "406" # high-frequency, 12 cores, 48  GB memory, 786 GB SSD
      region: "2" # Chicago
      ssh_keys:
      - wikidata-filter-key
