- hosts:
  - localhost
  gather_facts: no
  tasks:

  - name: Ensure server exists
    local_action:
      module: vultr_server
      name: wikidata-filter
      os: "Debian 10 x64 (buster)"
      plan: "405" # high-frequency, 8 cores, 32 GB memory, 512 GB SSD
      region: "2" # Chicago
      ssh_keys:
      - wikidata-filter-key
